### ISSUE TITLE
file not detected

### ISSUE THREAD

**Issue by JamesDAdams** [linuxserver/docker-gazee#8]
file not detected in the gazee.

**Comment by homerr** [comment]
Need more information.

**Comment by JamesDAdams** [comment]
I installe Gazee in Docker I configure the /comis in my hard drive but my comis it's not detected :(

My configuration it' good...

**Comment by JamesDAdams** [comment]
https://ibb.co/rytML4J
https://ibb.co/fMP50tX

**Comment by CHBMB** [comment]
Gonna close this as there's no way enough information to help and the screenshots provided show you've configured the comic location as `/test` not `/comis` as you originally stated.
